version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ejemplo
      MYSQL_DATABASE: banca_virtual
      MYSQL_USER: usuario
      MYSQL_PASSWORD: secreto
    ports:
      - "3306:3306"
